# https://vite.dev/guide/static-deploy.html#github-pages
name: Get & Process data, Build & Deploy app

on:
  push:
    branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true


jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Pip Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r 'requirements.txt'
        working-directory: 'jar2blockset'

      - name: Run JarFetcher
        run: |
          python -u '_jarfetcher.py' 'data'
        working-directory: 'jar2blockset'

      - name: Run Jar2BlockSet
        # We want to process the files in reverse order, so the older
        # MCJE versions will appear in the _blocksets.json the latest.
        # TODO: For now we also have to fix the pathes to be relative to provided JARs
        # instead of script itself, which is how j2bs should probably behave by default.
        run: |
          fs=(data/*.jar)
          IFS=$'\n' fss=($(printf "%s\n" "${fs[@]}" | sort -rV))
          unset IFS
          for f in "${fss[@]}"; do
            python -u '_main.py' "$f"
            rm "$f"
            sed -i 's|data/||' 'data/_blocksets.json'
          done
        working-directory: 'jar2blockset'


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          # https://stackoverflow.com/questions/68639588/github-actions-dependencies-lock-file-is-not-found-in-runners-path
          cache-dependency-path: 'vueblocks/package-lock.json'

      - name: Install NPM dependencies
        run: npm ci
        working-directory: 'vueblocks'

      - name: Move j2bs results to vb blocksets data
        run: |
          rm -rf '../../vueblocks/data/blocksets'
          mkdir -p '../../vueblocks/data/blocksets'
          mv -v * '../../vueblocks/data/blocksets'
        working-directory: 'jar2blockset/data'

      - name: Build VueBlocks
        run: npm run build
        working-directory: 'vueblocks'


      - name: Setup GH Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'vueblocks/dist'

      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v4
